[project]
name = "prettyneat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gym>=0.26.2",
    "matplotlib>=3.10.8",
    "mpi4py>=4.1.1",
    "numpy>=2.4.1",
]
